responses = {
    "intro": 'Please, choose your preferred language\nПожалуйста, выберите язык\n🙂',
    "about_me_rus": 'Бот для конвертации криптовалют, для списка комманд используйте /help',
    "about_me_eng": 'Bot for cryptocurrency convert, use /help to see available commands',
    "help_msg_rus": 'Доступные комманды\n/convert - перевод одной криптовалюты в другую валюту \n/currencies - доступные валюты для конвертации',
    "help_msg_eng": 'Available commands\n/convert - convert cryptocurrency into another currency \n/currencies - available currencies for convertation',
    "step_1_rus": 'Какую валюту ты хочешь конверитровать',
    "step_1_eng": 'What currency do you want to convert',
    "step_2_rus": 'В какую валюту ты хочешь конвертировать {}',
    "step_2_eng": 'To which currency you want to convert {}',
    "step_3_rus": 'Сколько {a} ты хочешь конвертировать{b}',
    "step_3_eng": 'How much of {a} you want to convert to {b}',
    "err_cur_rus": 'Неправильная валюта',
    "err_cur_eng": 'Wrong currency',
    "err_int_rus": 'Пожалуйста, используйте только число',
    "err_int_eng": 'Please, use a number',
    "err_zero_rus": 'Невозможно конвертировать 0 валюты',
    "err_zero_eng": 'Can`t convert 0 currency',
    "err_wrng_rus": 'Что-то пошло не так, пожалуйста, попробуйте позже',
    "err_wrng_eng": 'Something went wrong, please, try again later',
    "err_same_rus": 'Нельзя конверировать валюту в саму себя',
    "err_same_eng": 'Can`t convert currency into itself',
    "result_rus": '1{base} это {answer[q]}{q}',
    "result_eng": '1{base} is {answer[q]}{q}',
    "result_more_rus": '1{base} это {answer[q]}{q}, {a}{base} is {d}{q}',
    "result_more_eng": '1{base} is {answer[q]}{q}, {a}{base} is {d}{q}'
}
currency = {
    "биткоин": "BTC",
    "эфириум": "ETH",
    "доллар": "USD",
    "bitcoin": "BTC",
    "ethereum": "ETH",
    "dollar": "USD",
}
